[package]
name = "dev-hotstuff"
version = "0.1.0"
authors = ["贺梦杰 <njtech_hemengjie@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
